# Используем Node.js
FROM node:18

WORKDIR /app

# Копируем только package.json и устанавливаем зависимости без dev
COPY package.json package-lock.json ./
RUN npm install --omit=dev

# Копируем только скомпилированные файлы
COPY dist/ ./dist/
COPY .env ./

# Устанавливаем переменные окружения
ENV NODE_ENV=production
ENV DATABASE_URL=host.docker.internal 

RUN npm start
